// Seed import — port of reference article_seed.js. The committed seed file
// (article-seed/articles.js) is a browser script of the form:
//
//   window.App = window.App || {};
//   window.App.ArticleSeed = [ { ...json... }, ... ];
//
// We extract the JSON array by locating the `ArticleSeed =` assignment and
// bracket-slicing to the matching close — NEVER eval/vm: the file is data,
// and executing third-party JS server-side would be an injection surface.
// Idempotency comes from upsertArticles' url_hash dedup (no localStorage
// marker needed — the DB itself is the marker).

import { readFileSync } from 'node:fs';
import { upsertArticles } from './ingest.js';

// Seed source resolution order:
//   1. POSTER_SEED_PATH env var (deploy-time configuration)
//   2. a copy vendored into this repo at poster-app/data/article-seed.js
//   3. the reference Newsletter Automation checkout on the original dev machine
// importSeedArticles throws SEED_FILE_MISSING naming the resolved path if none exist.
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const VENDORED_SEED_PATH = fileURLToPath(new URL('../data/article-seed.js', import.meta.url));
const REFERENCE_REPO_SEED_PATH =
  'C:\\Users\\GT\\Documents\\test_UAT\\awareness-check\\awareness\\article-seed\\articles.js';

export const DEFAULT_SEED_PATH =
  process.env.POSTER_SEED_PATH
  || (existsSync(VENDORED_SEED_PATH) ? VENDORED_SEED_PATH : REFERENCE_REPO_SEED_PATH);

/**
 * Extract and parse the seed array from the reference file's JS source.
 * Exported for tests. Throws SEED_PARSE_FAILED on any structural surprise.
 */
export function parseSeedSource(source) {
  const text = String(source || '');
  const assign = text.match(/ArticleSeed\s*=\s*/);
  if (!assign) {
    const err = new Error('Seed file has no "ArticleSeed =" assignment — not a seed export?');
    err.code = 'SEED_PARSE_FAILED';
    throw err;
  }
  const start = text.indexOf('[', assign.index + assign[0].length - 1);
  if (start === -1) {
    const err = new Error('Seed file assignment is not an array literal');
    err.code = 'SEED_PARSE_FAILED';
    throw err;
  }
  // The array is pure JSON (auto-generated by exportArticleSeed), so the last
  // ']' in the file closes it; slicing to lastIndexOf is robust against any
  // trailing "];" / comment noise without needing a JS parser.
  const end = text.lastIndexOf(']');
  if (end <= start) {
    const err = new Error('Seed file array literal never closes');
    err.code = 'SEED_PARSE_FAILED';
    throw err;
  }
  let parsed;
  try {
    parsed = JSON.parse(text.slice(start, end + 1));
  } catch (e) {
    const err = new Error(`Seed array is not valid JSON: ${e.message}`);
    err.code = 'SEED_PARSE_FAILED';
    throw err;
  }
  if (!Array.isArray(parsed)) {
    const err = new Error('Seed payload is not an array');
    err.code = 'SEED_PARSE_FAILED';
    throw err;
  }
  return parsed;
}

/**
 * Import the committed seed set into SQLite with seeded=1.
 * Duplicate url_hash rows are merged (never duplicated) — safe to re-run.
 *
 * @param {object} opts { db, seedPath } — seedPath overrides the default
 *   reference-repo location (useful for tests and relocated checkouts).
 */
export function importSeedArticles({ db, seedPath = DEFAULT_SEED_PATH }) {
  let source;
  try {
    source = readFileSync(seedPath, 'utf8');
  } catch (e) {
    const err = new Error(`Seed file not readable at ${seedPath}: ${e.message}`);
    err.code = 'SEED_FILE_MISSING';
    throw err;
  }
  const seedArticles = parseSeedSource(source);

  // Field names in the seed match the reference IndexedDB records; ingest's
  // upsert maps them to snake_case columns (watchouts arrays JSON-stringified).
  const { saved, updated, skipped } = upsertArticles(db, seedArticles, { seeded: true });
  return { total: seedArticles.length, saved, updated, skipped };
}
