// CCPA/CPRA knowledge corpus — the California Consumer Privacy Act of 2018
// (CCPA) as amended by the California Privacy Rights Act of 2020 (CPRA),
// codified at Cal. Civ. Code §§1798.100 et seq. Each entry conforms to the
// KnowledgeEntry contract in ./schema.js (region 'US', framework 'CCPA').
//
// Content policy: summary/text are authoritative PARAPHRASE — plain-language,
// accurate, never a verbatim statute dump. Section numbers are approximate
// where noted; CPRA created/renumbered several provisions.

/** @type {import('./schema.js')} */
const entries = [
  // ─────────────────────────── Consumer rights ───────────────────────────
  {
    id: 'ccpa-right-to-know',
    framework: 'CCPA',
    citation: 'CCPA §1798.100 / §1798.110',
    level: 0,
    region: 'US',
    title: 'Right to Know / Access Personal Information',
    summary: 'California consumers can ask a business what personal information it collected about them, where it came from, why it was collected, and who it was shared with.',
    text: 'The right to know lets a consumer request the categories and specific pieces of personal information a business has collected, the categories of sources, the business or commercial purpose for collecting or selling it, and the categories of third parties to whom it was disclosed or sold. On a verifiable request, the business must disclose this for the 12-month period preceding the request (CPRA extends this beyond 12 months for data collected on or after Jan 1, 2022, where not impossible or disproportionate). Responses are generally due within 45 days, extendable once by another 45 days with notice.',
    obligations: ['Verify the requester\'s identity before disclosing personal information', 'Respond to access requests within 45 days (one 45-day extension allowed)', 'Provide the required categories and specific pieces of personal information free of charge, up to twice per year'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor, assessed by the CPPA or Attorney General.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['right to know', 'access request', 'data subject request', 'transparency', 'personal information', 'DSAR'],
    posterAngles: ['You have the right to ask any business what it knows about you', 'Recognise an access request and route it to the privacy team fast', 'Verify who is asking before you hand over personal information']
  },
  {
    id: 'ccpa-right-to-delete',
    framework: 'CCPA',
    citation: 'CCPA §1798.105',
    level: 0,
    region: 'US',
    title: 'Right to Delete Personal Information',
    summary: 'Consumers can ask a business to delete the personal information it collected from them, and the business must also direct its service providers to delete it.',
    text: 'On a verifiable deletion request, a business must delete the consumer\'s personal information from its records and instruct its service providers and contractors to do the same. The right is subject to statutory exceptions — for example, completing a transaction, detecting security incidents, complying with legal obligations, or exercising free speech. A business may deny deletion only where an exception genuinely applies, and must tell the consumer which exception it relied on.',
    obligations: ['Delete personal information on a verified consumer request unless an exception applies', 'Direct service providers and contractors to delete the same information', 'Document and disclose which statutory exception justifies any denial'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses', 'consumers', 'service-providers'],
    topics: ['right to delete', 'erasure', 'deletion request', 'data subject request', 'retention'],
    posterAngles: ['When someone asks you to delete their data, delete it everywhere', 'A deletion request means telling your vendors to erase it too', 'Never "lose" or quietly drop a delete request — it is a legal duty']
  },
  {
    id: 'ccpa-right-to-correct',
    framework: 'CCPA',
    citation: 'CPRA §1798.106',
    level: 0,
    region: 'US',
    title: 'Right to Correct Inaccurate Personal Information',
    summary: 'A CPRA addition: consumers can ask a business to fix inaccurate personal information it holds about them.',
    text: 'The CPRA added the right to correction. On a verifiable request, a business must use commercially reasonable efforts to correct inaccurate personal information a consumer identifies, taking into account the nature of the data and the purposes of processing. The business must instruct service providers and contractors to make the correction as well.',
    obligations: ['Use commercially reasonable efforts to correct inaccurate personal information on request', 'Verify the request and the claimed inaccuracy before acting', 'Direct service providers and contractors to apply the correction'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['right to correct', 'rectification', 'data accuracy', 'CPRA', 'data subject request'],
    posterAngles: ['People can ask you to fix wrong data about them — and you must try', 'Acting on inaccurate data can harm real people; correct it', 'Route correction requests through the proper channel, not ad hoc']
  },
  {
    id: 'ccpa-right-to-opt-out',
    framework: 'CCPA',
    citation: 'CCPA §1798.120',
    level: 0,
    region: 'US',
    title: 'Right to Opt Out of Sale or Sharing',
    summary: 'Consumers can direct a business to stop selling their personal information or sharing it for cross-context behavioural advertising.',
    text: 'The right to opt out lets a consumer tell a business to stop selling their personal information and, under the CPRA, to stop "sharing" it for cross-context behavioural advertising. A business that sells or shares personal information must provide a clear "Do Not Sell or Share My Personal Information" link and honour opt-out requests, including opt-out preference signals like Global Privacy Control. For consumers under 16, the business must obtain affirmative opt-in consent before selling or sharing (opt-in for 13-15 by the minor; parental consent under 13).',
    obligations: ['Provide a clear "Do Not Sell or Share My Personal Information" link', 'Honour opt-out requests without requiring account creation', 'Obtain affirmative opt-in consent to sell/share data of consumers under 16'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or any violation involving a consumer under 16.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['opt-out', 'do not sell', 'sharing', 'cross-context behavioural advertising', 'sale of data', 'minors'],
    posterAngles: ['Californians can say "do not sell my data" — and you must comply', 'Selling a teen\'s data needs their opt-in, not just no objection', 'An opt-out link that does nothing is itself a violation']
  },
  {
    id: 'ccpa-right-to-limit-spi',
    framework: 'CCPA',
    citation: 'CPRA §1798.121',
    level: 0,
    region: 'US',
    title: 'Right to Limit Use of Sensitive Personal Information',
    summary: 'A CPRA right: consumers can tell a business to limit its use of their sensitive personal information to what is necessary to provide the service.',
    text: 'The CPRA created a distinct category of sensitive personal information (SPI) and a right to limit its use. Consumers can direct a business to use their SPI only for purposes necessary to deliver the requested goods or services (and certain permitted operational uses). Where a business uses SPI beyond those purposes, it must post a "Limit the Use of My Sensitive Personal Information" link and honour limitation requests.',
    obligations: ['Post a "Limit the Use of My Sensitive Personal Information" link where SPI is used beyond necessary purposes', 'Restrict SPI use to what is reasonably necessary once a consumer exercises the right', 'Honour limitation requests, including via opt-out preference signals'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['sensitive personal information', 'right to limit', 'SPI', 'CPRA', 'purpose limitation'],
    posterAngles: ['Sensitive data — health, precise location, SSN — gets extra protection', 'Consumers can cap how you use their most sensitive information', 'Only use sensitive data for what the service actually needs']
  },
  {
    id: 'ccpa-right-non-discrimination',
    framework: 'CCPA',
    citation: 'CCPA §1798.125',
    level: 0,
    region: 'US',
    title: 'Right to Non-Discrimination',
    summary: 'A business cannot punish consumers for exercising their privacy rights by denying service, charging more, or degrading quality.',
    text: 'The right to non-discrimination prohibits a business from retaliating against a consumer who exercises a CCPA right — for example by denying goods or services, charging different prices, or providing a lower quality of service. A business may still offer financial incentives or price differences that are reasonably related to the value of the consumer\'s data, provided they are not unjust, unreasonable, coercive, or usurious, and require opt-in consent for the incentive.',
    obligations: ['Never deny service, degrade quality, or raise prices because a consumer exercised a privacy right', 'Only offer data-value incentives that are non-coercive and reasonably related to the data\'s value', 'Obtain opt-in consent before enrolling a consumer in a financial-incentive program'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['non-discrimination', 'retaliation', 'financial incentives', 'consumer rights', 'pay-for-privacy'],
    posterAngles: ['Exercising a privacy right must never cost the customer their service', 'You cannot punish someone for opting out of data sale', 'Loyalty perks are fine — coercing data out of people is not']
  },
  {
    id: 'ccpa-right-portability',
    framework: 'CCPA',
    citation: 'CCPA §1798.100(d)',
    level: 0,
    region: 'US',
    title: 'Right to Data Portability',
    summary: 'When responding to an access request, a business must provide the personal information in a portable, readily usable format the consumer can transmit elsewhere.',
    text: 'Data portability under the CCPA is delivered through the right to know: when a consumer requests the specific pieces of personal information collected, and provides it electronically, the business must supply it in a portable and, to the extent technically feasible, readily usable format that allows the consumer to transmit the information to another entity without hindrance.',
    obligations: ['Provide requested personal information in a portable, readily usable format', 'Deliver electronic responses in a machine-readable form where feasible', 'Avoid formats that hinder a consumer from moving their data'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['data portability', 'right to know', 'machine-readable', 'interoperability', 'access request'],
    posterAngles: ['Give people their data back in a form they can actually reuse', 'Portability means no locked-in, unusable data dumps', 'Access rights include the right to take your data elsewhere']
  },

  // ───────────────────────── Core definitions ─────────────────────────
  {
    id: 'ccpa-def-personal-information',
    framework: 'CCPA',
    citation: 'CCPA §1798.140(v)',
    level: 0,
    region: 'US',
    title: 'Definition — Personal Information',
    summary: 'Personal information is any information that identifies, relates to, or could reasonably be linked with a particular consumer or household.',
    text: 'The CCPA defines personal information broadly: information that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or household. It includes identifiers (name, IP address, account IDs), commercial and browsing history, geolocation, biometric data, and inferences drawn to create a profile. Publicly available and deidentified or aggregated information is excluded.',
    obligations: ['Treat identifiers, browsing data, geolocation, and inferences as regulated personal information', 'Do not assume data is exempt just because it lacks a name', 'Apply CCPA protections at the household level, not only per individual'],
    penalties: null,
    appliesTo: ['businesses'],
    topics: ['personal information', 'definition', 'identifiers', 'household', 'inferences', 'PII'],
    posterAngles: ['"Personal information" is far broader than just names and emails', 'An IP address or a device profile counts as personal information', 'If it can be linked to a person or household, protect it']
  },
  {
    id: 'ccpa-def-sensitive-pi',
    framework: 'CCPA',
    citation: 'CPRA §1798.140(ae)',
    level: 0,
    region: 'US',
    title: 'Definition — Sensitive Personal Information',
    summary: 'A CPRA category covering especially sensitive data such as SSNs, precise geolocation, health, sexual orientation, race, and account credentials.',
    text: 'Sensitive personal information (SPI) is a CPRA-defined subset including a consumer\'s Social Security, driver\'s license, or passport number; account log-in with password; precise geolocation; racial or ethnic origin; religious or philosophical beliefs; union membership; contents of mail, email, and texts; genetic data; biometric data used to uniquely identify; health information; and data about sex life or sexual orientation. SPI triggers the right to limit its use and heightened handling expectations.',
    obligations: ['Identify and inventory sensitive personal information separately', 'Apply the right-to-limit mechanism where SPI is used beyond necessary purposes', 'Provide extra safeguards for SSNs, credentials, health, and precise location'],
    penalties: null,
    appliesTo: ['businesses'],
    topics: ['sensitive personal information', 'SPI', 'definition', 'CPRA', 'SSN', 'geolocation', 'health data', 'credentials'],
    posterAngles: ['SSNs, passwords, precise location and health data are extra-sensitive', 'Know which of your data fields count as sensitive under CPRA', 'Sensitive data deserves stricter access and stricter limits']
  },
  {
    id: 'ccpa-def-sale',
    framework: 'CCPA',
    citation: 'CCPA §1798.140(ad)',
    level: 0,
    region: 'US',
    title: 'Definition — Sale',
    summary: 'A "sale" is disclosing personal information to a third party for monetary or other valuable consideration — not only for cash.',
    text: 'Under the CCPA, "sell" means selling, renting, releasing, disclosing, disseminating, making available, or transferring a consumer\'s personal information to a third party for monetary or other valuable consideration. The "valuable consideration" wording means many data-sharing arrangements that involve no direct payment can still be sales. Transfers to service providers under a compliant contract, or as part of a merger, are generally excluded.',
    obligations: ['Recognise that non-cash data exchanges can qualify as a "sale"', 'Map all outbound data flows to determine which are sales', 'Provide opt-out and the required link wherever a sale occurs'],
    penalties: null,
    appliesTo: ['businesses'],
    topics: ['sale', 'definition', 'valuable consideration', 'third party', 'opt-out'],
    posterAngles: ['A "sale" of data does not require money changing hands', 'Trading data for services can legally count as selling it', 'Know your outbound data flows — some may be regulated sales']
  },
  {
    id: 'ccpa-def-sharing',
    framework: 'CCPA',
    citation: 'CPRA §1798.140(ah)',
    level: 0,
    region: 'US',
    title: 'Definition — Sharing',
    summary: 'A CPRA term: "sharing" is disclosing personal information for cross-context behavioural advertising, whether or not for payment.',
    text: 'The CPRA added "sharing" to close a loophole: it means disclosing a consumer\'s personal information to a third party for cross-context behavioural advertising, whether or not for money or other consideration. This captured targeted-ad data flows that businesses argued were not "sales." The opt-out right and the "Do Not Sell or Share" link cover sharing as well as sale.',
    obligations: ['Treat data disclosed for targeted advertising as "sharing" subject to opt-out', 'Include sharing in the "Do Not Sell or Share My Personal Information" link', 'Stop sharing for behavioural advertising when a consumer opts out'],
    penalties: null,
    appliesTo: ['businesses'],
    topics: ['sharing', 'definition', 'cross-context behavioural advertising', 'CPRA', 'targeted advertising', 'opt-out'],
    posterAngles: ['"Sharing" data for targeted ads is regulated even without payment', 'CPRA closed the loophole: targeted-ad data flows count', 'Opt-out covers both selling and sharing for advertising']
  },
  {
    id: 'ccpa-def-business',
    framework: 'CCPA',
    citation: 'CCPA §1798.140(d)',
    level: 0,
    region: 'US',
    title: 'Definition — Business',
    summary: 'A "business" is a for-profit entity doing business in California that meets one of the CCPA\'s size or data-volume thresholds.',
    text: 'A "business" is a for-profit legal entity that collects consumers\' personal information, does business in California, and meets at least one threshold: gross annual revenue over $25 million; buys, sells, or shares the personal information of 100,000 or more consumers or households annually; or derives 50% or more of annual revenue from selling or sharing personal information. The business is the party that determines the purposes and means of processing and bears primary CCPA responsibility.',
    obligations: ['Determine whether your entity meets a CCPA business threshold', 'As the business, take primary responsibility for CCPA compliance', 'Include controlled affiliates that share branding within scope'],
    penalties: null,
    appliesTo: ['businesses'],
    topics: ['business', 'definition', 'thresholds', 'applicability', 'scope'],
    posterAngles: ['Not every company is covered — thresholds decide who is a "business"', 'The "business" is the one calling the shots on your data', 'Revenue or data volume can pull a company into CCPA scope']
  },
  {
    id: 'ccpa-def-service-provider',
    framework: 'CCPA',
    citation: 'CCPA §1798.140(ag)',
    level: 0,
    region: 'US',
    title: 'Definition — Service Provider',
    summary: 'A service provider processes personal information for a business under a written contract that restricts it to the business\'s purposes.',
    text: 'A service provider is a person or entity that processes personal information on behalf of a business under a written contract prohibiting it from selling or sharing the data, retaining or using it outside the direct business relationship, or combining it with data from other sources (except as permitted). Proper service-provider status keeps disclosures from being treated as "sales."',
    obligations: ['Bind every service provider with a compliant written contract', 'Restrict the service provider to the business\'s specified purposes', 'Prohibit the service provider from selling, sharing, or repurposing the data'],
    penalties: null,
    appliesTo: ['businesses', 'service-providers'],
    topics: ['service provider', 'definition', 'processor', 'contracts', 'vendor'],
    posterAngles: ['Vendors that handle your data must be locked to your purposes only', 'A proper service-provider contract keeps a transfer from being a sale', 'Never let a service provider repurpose the data you hand them']
  },
  {
    id: 'ccpa-def-contractor',
    framework: 'CCPA',
    citation: 'CPRA §1798.140(j)',
    level: 0,
    region: 'US',
    title: 'Definition — Contractor',
    summary: 'A contractor is a party to whom a business makes personal information available for a business purpose under a CCPA-compliant contract.',
    text: 'The CPRA added "contractor" alongside "service provider." A contractor is a person to whom the business makes personal information available for a business purpose under a written contract containing the same core restrictions — no selling or sharing, use limited to the specified purposes, and a certification that the contractor understands and will comply. The distinction is largely technical; both are constrained processors of the business\'s data.',
    obligations: ['Require contractors to certify they understand and will follow CCPA restrictions', 'Include the mandated flow-down clauses in every contractor agreement', 'Limit contractor use of personal information to the contracted business purpose'],
    penalties: null,
    appliesTo: ['businesses', 'contractors'],
    topics: ['contractor', 'definition', 'CPRA', 'contracts', 'processor'],
    posterAngles: ['Contractors who touch your data must certify CCPA compliance', 'Like service providers, contractors are locked to your purposes', 'The contract certification is not boilerplate — it is required']
  },
  {
    id: 'ccpa-def-third-party',
    framework: 'CCPA',
    citation: 'CCPA §1798.140(ai)',
    level: 0,
    region: 'US',
    title: 'Definition — Third Party',
    summary: 'A third party is anyone who is not the business itself nor a service provider or contractor bound by a compliant contract.',
    text: 'A third party is a person or entity that is not the business that collects the personal information and is not a service provider or contractor operating under a CCPA-compliant contract. Disclosing personal information to a third party for consideration is a "sale," and disclosing it for behavioural advertising is "sharing." Getting the third-party classification wrong is how many businesses inadvertently make regulated sales.',
    obligations: ['Classify each data recipient as business, service provider, contractor, or third party', 'Treat disclosures to unbound third parties as potential sales or sharing', 'Provide opt-out mechanisms wherever third-party disclosures occur'],
    penalties: null,
    appliesTo: ['businesses'],
    topics: ['third party', 'definition', 'sale', 'sharing', 'classification'],
    posterAngles: ['If a recipient is not under a proper contract, they are a "third party"', 'Handing data to a third party can quietly become a sale', 'Classify every data recipient correctly before you share']
  },

  // ───────────────────────── Business obligations ─────────────────────────
  {
    id: 'ccpa-notice-at-collection',
    framework: 'CCPA',
    citation: 'CCPA §1798.100(b)',
    level: 0,
    region: 'US',
    title: 'Notice at Collection',
    summary: 'At or before the point of collection, a business must tell consumers the categories of personal information collected and the purposes for which it will be used.',
    text: 'A business must provide a notice at collection — at or before it collects personal information — listing the categories of personal information and sensitive personal information collected, the purposes for each, whether the data is sold or shared, and the retention period for each category. The notice must be readily available where the data is collected (for example on a web form or at a point of sale) and cannot be used to collect data for undisclosed purposes.',
    obligations: ['Present a notice at or before the point of collection', 'List the categories collected, purposes, and retention periods', 'Never collect personal information for purposes not disclosed in the notice'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses'],
    topics: ['notice at collection', 'transparency', 'purpose disclosure', 'retention', 'collection'],
    posterAngles: ['Tell people what you collect and why — before you collect it', 'No hidden purposes: the notice at collection sets the limits', 'A form that grabs data with no notice is out of compliance']
  },
  {
    id: 'ccpa-privacy-policy',
    framework: 'CCPA',
    citation: 'CCPA §1798.130 / §1798.135',
    level: 0,
    region: 'US',
    title: 'Privacy Policy Requirements',
    summary: 'A business must maintain an online privacy policy describing consumers\' rights and how to exercise them, updated at least every 12 months.',
    text: 'The CCPA requires a comprehensive, accessible privacy policy that describes the consumer rights available (know, delete, correct, opt-out, limit, non-discrimination), the methods for submitting requests, the categories of personal and sensitive information collected, sold, or shared in the past 12 months, and the sources and purposes. The policy must be updated at least once every 12 months and be reasonably accessible to consumers with disabilities.',
    obligations: ['Publish and maintain a CCPA-compliant online privacy policy', 'Describe every consumer right and how to exercise it', 'Review and update the policy at least every 12 months'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses'],
    topics: ['privacy policy', 'transparency', 'consumer rights', 'disclosure', 'accessibility'],
    posterAngles: ['A stale privacy policy is a compliance gap — refresh it yearly', 'The privacy policy must spell out every right and how to use it', 'Make the policy accessible to everyone, including assistive tech users']
  },
  {
    id: 'ccpa-do-not-sell-link',
    framework: 'CCPA',
    citation: 'CCPA §1798.135',
    level: 0,
    region: 'US',
    title: '"Do Not Sell or Share My Personal Information" Link',
    summary: 'A business that sells or shares personal information must post a clear, conspicuous opt-out link on its homepage.',
    text: 'A business that sells or shares personal information must provide a clear and conspicuous "Do Not Sell or Share My Personal Information" link on its internet homepage that lets consumers opt out. Where a business uses sensitive personal information beyond permitted purposes, it must also post a "Limit the Use of My Sensitive Personal Information" link. Businesses may instead honour opt-out preference signals and, in some cases, provide a single, clearly labelled link covering both rights.',
    obligations: ['Post a clear and conspicuous "Do Not Sell or Share" link on the homepage', 'Add a "Limit the Use of My Sensitive Personal Information" link where SPI is used beyond necessary purposes', 'Ensure the link actually processes opt-out requests, not just displays'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses'],
    topics: ['do not sell', 'opt-out link', 'homepage', 'sharing', 'sensitive personal information'],
    posterAngles: ['The opt-out link belongs on the homepage, clear and obvious', 'A "Do Not Sell" link that fails to opt people out is a violation', 'Selling sensitive data means an extra "limit use" link too']
  },
  {
    id: 'ccpa-gpc-opt-out-signals',
    framework: 'CCPA',
    citation: 'CPRA §1798.135 / CCPA Regs §7025',
    level: 1,
    region: 'US',
    title: 'Opt-Out Preference Signals (Global Privacy Control)',
    summary: 'Businesses must treat a browser-level opt-out preference signal, such as Global Privacy Control, as a valid opt-out of sale and sharing.',
    text: 'CPRA and the CCPA regulations require businesses to honour opt-out preference signals — a user setting or extension like Global Privacy Control (GPC) that automatically communicates a consumer\'s choice to opt out of the sale and sharing of personal information. When a business detects a valid signal, it must treat it as a request to opt out for that browser or device, and, if it can associate the signal with a known consumer, apply it to that consumer\'s account. The signal must be honoured without asking the consumer to take extra steps.',
    obligations: ['Detect and honour Global Privacy Control and other valid opt-out preference signals', 'Apply the signal to associated known consumers, not just the browser', 'Do not require additional confirmation steps to give effect to a valid signal'],
    penalties: 'Enforced as a failure to honour opt-out: up to $2,500 per violation, or $7,500 per intentional violation.',
    appliesTo: ['businesses'],
    topics: ['GPC', 'Global Privacy Control', 'opt-out preference signal', 'browser signal', 'automated opt-out', 'sharing'],
    posterAngles: ['A browser "do not sell" signal is a legally binding opt-out', 'Global Privacy Control means honouring the choice automatically', 'Do not make people click twice to enforce a signal you already got']
  },
  {
    id: 'ccpa-purpose-limitation-minimization',
    framework: 'CCPA',
    citation: 'CPRA §1798.100(c)',
    level: 0,
    region: 'US',
    title: 'Purpose Limitation & Data Minimisation',
    summary: 'A business may collect and use personal information only as reasonably necessary and proportionate to the disclosed purposes.',
    text: 'The CPRA added core data-minimisation and purpose-limitation principles: a business\'s collection, use, retention, and sharing of personal information must be reasonably necessary and proportionate to achieve the purposes for which it was collected, or another compatible disclosed purpose. Collecting extra data "just in case," or repurposing data for unrelated uses, is not permitted absent a new disclosure and, where required, consent.',
    obligations: ['Collect only personal information reasonably necessary for the disclosed purpose', 'Limit use and retention to what is proportionate to that purpose', 'Obtain a new disclosure or consent before repurposing data for an incompatible use'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation or violation involving a minor.',
    appliesTo: ['businesses'],
    topics: ['data minimisation', 'purpose limitation', 'proportionality', 'CPRA', 'retention'],
    posterAngles: ['Collect only what you truly need — nothing "just in case"', 'Data grabbed for one purpose cannot quietly serve another', 'Less data collected means less data to leak or misuse']
  },
  {
    id: 'ccpa-reasonable-security',
    framework: 'CCPA',
    citation: 'CPRA §1798.100(e)',
    level: 0,
    region: 'US',
    title: 'Reasonable Security',
    summary: 'A business must implement reasonable security procedures and practices appropriate to the nature of the personal information it holds.',
    text: 'The CCPA requires a business that collects personal information to implement reasonable security procedures and practices appropriate to the nature of the information, to protect it from unauthorised access, destruction, use, modification, or disclosure. Failing to maintain reasonable security is also the trigger for the private right of action when a breach of certain unencrypted or unredacted personal information occurs.',
    obligations: ['Implement security controls appropriate to the sensitivity of the data', 'Encrypt or redact sensitive personal information where feasible', 'Maintain safeguards continuously, not just at collection'],
    penalties: 'Statutory damages of $100–$750 per consumer per incident (or actual damages) under the private right of action for breaches caused by unreasonable security.',
    appliesTo: ['businesses'],
    topics: ['reasonable security', 'safeguards', 'encryption', 'breach', 'data protection'],
    posterAngles: ['"Reasonable security" is a legal duty, not an IT nice-to-have', 'Unencrypted data that leaks can trigger lawsuits and damages', 'Every shortcut around a control raises the breach bill']
  },
  {
    id: 'ccpa-service-provider-contracts',
    framework: 'CCPA',
    citation: 'CCPA §1798.100(d) / §1798.140',
    level: 0,
    region: 'US',
    title: 'Service-Provider & Contractor Contracts',
    summary: 'Contracts with service providers, contractors, and third parties must contain the CCPA-mandated data-protection terms.',
    text: 'Whenever a business discloses personal information to a service provider, contractor, or third party, it must have a contract that prohibits selling or sharing the data, limits use to the specified business purposes, requires the same level of privacy protection, grants the business rights to monitor compliance, and requires notification if the recipient can no longer meet its obligations. Missing or non-compliant contracts convert otherwise-permitted disclosures into regulated sales.',
    obligations: ['Include all CCPA-required flow-down clauses in data-sharing contracts', 'Prohibit recipients from selling, sharing, or repurposing the data', 'Retain rights to monitor and audit recipient compliance'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation.',
    appliesTo: ['businesses', 'service-providers', 'contractors'],
    topics: ['contracts', 'service provider', 'contractor', 'data processing agreement', 'flow-down clauses'],
    posterAngles: ['No compliant contract? Then sharing data may be an illegal sale', 'Data-sharing contracts must ban selling and repurposing', 'Confirm the paperwork before you hand any data to a vendor']
  },
  {
    id: 'ccpa-records-training',
    framework: 'CCPA',
    citation: 'CCPA Regs §7100 / §7101',
    level: 1,
    region: 'US',
    title: 'Records & Employee Training',
    summary: 'Businesses must keep records of consumer requests and train staff who handle personal information or consumer inquiries.',
    text: 'The CCPA regulations require businesses to maintain records of consumer requests and how they responded for at least 24 months, and to train all individuals responsible for handling consumer inquiries about the business\'s CCPA obligations and how to direct consumers to exercise their rights. Businesses that handle the personal information of 10 million or more consumers annually face additional metrics and public-reporting duties.',
    obligations: ['Retain records of consumer requests and responses for at least 24 months', 'Train staff who handle consumer inquiries on CCPA rights and processes', 'Publish request-handling metrics where the large-volume threshold applies'],
    penalties: 'Up to $2,500 per violation, or $7,500 per intentional violation.',
    appliesTo: ['businesses', 'workforce'],
    topics: ['recordkeeping', 'training', 'consumer requests', 'metrics', 'accountability'],
    posterAngles: ['Anyone fielding customer requests needs CCPA training', 'Keep a record of every privacy request and how you handled it', 'Untrained staff who mishandle a request create legal exposure']
  },

  // ───────────────────────── CPRA additions ─────────────────────────
  {
    id: 'ccpa-cppa-agency',
    framework: 'CCPA',
    citation: 'CPRA §1798.199.10 et seq.',
    level: 1,
    region: 'US',
    title: 'California Privacy Protection Agency (CPPA)',
    summary: 'The CPRA created the CPPA, a dedicated agency with rulemaking, investigation, and enforcement authority over California privacy law.',
    text: 'The CPRA established the California Privacy Protection Agency (CPPA), the first dedicated data-protection regulator in the United States. The CPPA has full administrative power to adopt regulations, investigate possible violations, hold hearings, and impose administrative fines, sharing enforcement authority with the California Attorney General. The agency issues the detailed CCPA regulations that flesh out the statute — for example on opt-out signals, risk assessments, and automated decision-making.',
    obligations: ['Track CPPA rulemaking and updated regulations, not just the statute', 'Cooperate with CPPA investigations and information requests', 'Treat CPPA administrative fines as an enforcement risk alongside AG action'],
    penalties: 'CPPA may levy administrative fines up to $2,500 per violation or $7,500 per intentional violation or minor-related violation.',
    appliesTo: ['businesses'],
    topics: ['CPPA', 'California Privacy Protection Agency', 'regulator', 'enforcement', 'rulemaking', 'CPRA'],
    posterAngles: ['California has its own privacy watchdog — the CPPA — with real teeth', 'The CPPA writes the rules and can fine you directly', 'Watch CPPA regulations, not just the statute, for what changes']
  },
  {
    id: 'ccpa-risk-assessments-audits',
    framework: 'CCPA',
    citation: 'CPRA §1798.185(a)(15) / CPPA Regs',
    level: 1,
    region: 'US',
    title: 'Risk Assessments & Cybersecurity Audits',
    summary: 'The CPRA directs regulations requiring businesses whose processing poses significant risk to conduct risk assessments and annual cybersecurity audits.',
    text: 'The CPRA authorised the CPPA to require businesses whose processing of personal information presents significant risk to consumers\' privacy or security to (1) perform regular risk assessments weighing the benefits of processing against the risks to consumers, and submit them to the agency, and (2) complete an annual, independent cybersecurity audit. The CPPA\'s regulations define the triggers and content, focusing on high-risk activities like large-scale sensitive-data processing, profiling, and automated decision-making.',
    obligations: ['Conduct and document risk assessments for high-risk processing', 'Complete an independent annual cybersecurity audit where required', 'Submit risk assessments to the CPPA as its regulations direct'],
    penalties: 'Failure to conduct required assessments or audits is enforceable: up to $2,500 per violation, or $7,500 per intentional violation.',
    appliesTo: ['businesses'],
    topics: ['risk assessment', 'cybersecurity audit', 'CPRA', 'high-risk processing', 'profiling', 'accountability'],
    posterAngles: ['High-risk data processing now requires formal risk assessments', 'An annual cybersecurity audit is becoming a legal expectation', 'Assess the risk before you launch, not after a breach']
  },
  {
    id: 'ccpa-automated-decision-making',
    framework: 'CCPA',
    citation: 'CPRA §1798.185(a)(16) / CPPA Regs',
    level: 1,
    region: 'US',
    title: 'Automated Decision-Making Technology',
    summary: 'The CPRA gives consumers rights around automated decision-making, including access to logic and the ability to opt out of certain uses.',
    text: 'The CPRA directed the CPPA to issue regulations governing automated decision-making technology (ADMT), including profiling. Under the emerging rules, consumers gain the right to access meaningful information about the logic involved in automated decisions that produce legal or similarly significant effects, and, in defined situations, the right to opt out of the use of ADMT. Businesses must give pre-use notice and, in some cases, allow the consumer to appeal to a human.',
    obligations: ['Provide meaningful information about the logic of significant automated decisions', 'Offer opt-out or human-review rights where the regulations require', 'Give pre-use notice before applying ADMT to consumers'],
    penalties: 'Non-compliance is enforceable under the general CCPA penalties: up to $2,500, or $7,500 per intentional violation.',
    appliesTo: ['businesses'],
    topics: ['automated decision-making', 'ADMT', 'profiling', 'algorithmic transparency', 'CPRA', 'opt-out'],
    posterAngles: ['People can ask how an algorithm made a decision about them', 'Automated decisions with big impact carry notice and opt-out duties', 'Profiling is regulated — transparency is now the expectation']
  },

  // ───────────────────────── Enforcement & penalties ─────────────────────────
  {
    id: 'ccpa-civil-penalties',
    framework: 'CCPA',
    citation: 'CCPA §1798.155',
    level: 0,
    region: 'US',
    title: 'Civil Penalties & Enforcement',
    summary: 'The CPPA and Attorney General can impose civil penalties of up to $2,500 per violation, rising to $7,500 for intentional or minor-related violations.',
    text: 'The CCPA is enforced by the California Privacy Protection Agency and the Attorney General. They can seek civil penalties of up to $2,500 for each violation and up to $7,500 for each intentional violation or each violation involving the personal information of a consumer under 16. Because penalties are assessed per violation — and a single incident can affect many consumers — total exposure can be very large. The CPRA removed the original 30-day cure period for most violations, so businesses can no longer count on a grace window.',
    obligations: ['Treat each affected consumer as a potential separate violation', 'Do not rely on a cure period — CPRA largely removed it', 'Prioritise fixing violations involving minors, which carry the higher penalty'],
    penalties: 'Up to $2,500 per violation; up to $7,500 per intentional violation or violation involving a consumer under 16.',
    appliesTo: ['businesses'],
    topics: ['civil penalties', 'enforcement', 'fines', 'cure period', 'CPPA', 'attorney general'],
    posterAngles: ['Fines are per violation — one incident can multiply fast', 'Intentional slips and minors\' data cost $7,500 each', 'No more automatic grace period — fix issues before they compound']
  },
  {
    id: 'ccpa-private-right-of-action',
    framework: 'CCPA',
    citation: 'CCPA §1798.150',
    level: 0,
    region: 'US',
    title: 'Private Right of Action for Data Breaches',
    summary: 'Consumers can sue directly for breaches of certain unencrypted personal information caused by a business\'s failure to maintain reasonable security.',
    text: 'The CCPA grants a limited private right of action: consumers whose nonencrypted and nonredacted personal information (specific categories such as name plus SSN, financial account, or medical information) is subject to unauthorised access and exfiltration, theft, or disclosure due to a business\'s failure to maintain reasonable security can sue. They may recover statutory damages between $100 and $750 per consumer per incident, or actual damages if greater, plus injunctive relief. This is the main avenue for class-action exposure under the law.',
    obligations: ['Maintain reasonable security to avoid statutory-damages exposure', 'Encrypt or redact the covered sensitive data categories', 'Respond quickly to any suspected breach to limit affected-consumer counts'],
    penalties: 'Statutory damages of $100–$750 per consumer per incident, or actual damages if greater, plus injunctive relief.',
    appliesTo: ['businesses', 'consumers'],
    topics: ['private right of action', 'data breach', 'statutory damages', 'class action', 'unencrypted data', 'reasonable security'],
    posterAngles: ['A breach of unencrypted data can put you in a class-action lawsuit', 'Each affected person can claim up to $750 — do the math on a breach', 'Encryption is the cheapest insurance against breach lawsuits']
  }
];

export default entries;
