// Seed import tests: parse the reference article-seed/articles.js format
// (window.App.ArticleSeed = [...json...];) from a temp fixture, import into
// SQLite with seeded=1, and stay idempotent across re-runs.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Database from 'better-sqlite3';
import { migrate } from '../../backend/db.js';
import { parseSeedSource, importSeedArticles } from '../../rag/seed_import.js';

// Mirrors the committed reference file byte-for-byte in structure: banner
// comment, window.App guard, JSON array assignment with aiProcessed/threatLevel
// fields the SQLite schema partially drops.
const SEED_FIXTURE = `// AUTO-GENERATED by App.DB.exportArticleSeed() — do not hand-edit.
// Committed starter article set, seeded into every user's DB on first launch.
window.App = window.App || {};
window.App.ArticleSeed = [{"title":"eBanking Phishing Delivered Through IPv4-Mapped IPv6 Address, (Fri, Jun 19th)","source":"SANS ISC","sourceId":"sansisc","url":"https://isc.sans.edu/diary/rss/33090","description":"I detected an interesting phishing email this morning. It targets a major Belgian bank:\\n","summary":"A phishing email targeting a major Belgian bank has been detected.","watchouts":["Verify emails claiming to be from banks","Check email sender addresses carefully","Report suspicious emails to your manager"],"pubDate":"2026-06-19","type":"Phishing","threatLevel":3,"relevanceScore":10,"tier":1,"aiProcessed":true},{"title":"That data breach alert might be a trap","source":"WeLiveSecurity (ESET)","sourceId":"welivesec","url":"https://www.welivesecurity.com/en/scams/data-breach-alert-might-be-trap/","description":"Ignoring a real breach notification invites risk, but falling for a bogus one could be even worse. Stop reacting on autopilot.","summary":null,"watchouts":["Change passwords for affected services and reused logins","Turn on MFA where the service still allows it"],"pubDate":"2026-04-17","type":"Data Breach","threatLevel":3,"relevanceScore":5,"tier":3,"aiProcessed":false}];
`;

function writeFixture(content, name = 'articles.js') {
  const dir = mkdtempSync(join(tmpdir(), 'postter-seed-'));
  const path = join(dir, name);
  writeFileSync(path, content, 'utf8');
  return path;
}

test('parseSeedSource extracts the JSON array without eval', () => {
  const parsed = parseSeedSource(SEED_FIXTURE);
  assert.equal(parsed.length, 2);
  assert.equal(parsed[0].sourceId, 'sansisc');
  assert.equal(parsed[1].type, 'Data Breach');
  assert.deepEqual(parsed[1].watchouts.length, 2);
});

test('importSeedArticles maps fields, sets seeded=1, and is idempotent', () => {
  const db = new Database(':memory:');
  migrate(db);
  const seedPath = writeFixture(SEED_FIXTURE);

  const first = importSeedArticles({ db, seedPath });
  assert.equal(first.total, 2);
  assert.equal(first.saved, 2);
  assert.equal(first.skipped, 0);

  const rows = db.prepare('SELECT * FROM articles ORDER BY id').all();
  assert.equal(rows.length, 2);
  assert.ok(rows.every((r) => r.seeded === 1));
  assert.equal(rows[0].source_id, 'sansisc');
  assert.equal(rows[0].threat_level, 3);
  assert.equal(rows[0].pub_date, '2026-06-19');
  assert.deepEqual(JSON.parse(rows[0].watchouts).length, 3);
  assert.equal(rows[0].summary, 'A phishing email targeting a major Belgian bank has been detected.');

  // re-run: url_hash dedup merges instead of duplicating
  const second = importSeedArticles({ db, seedPath });
  assert.equal(second.saved, 0);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM articles').get().n, 2);
  // enrichment survives the merge
  assert.equal(db.prepare('SELECT summary FROM articles WHERE id = 1').get().summary,
    'A phishing email targeting a major Belgian bank has been detected.');
});

test('missing seed file raises SEED_FILE_MISSING with the attempted path', () => {
  const db = new Database(':memory:');
  migrate(db);
  const ghost = join(tmpdir(), 'postter-seed-does-not-exist', 'articles.js');
  assert.throws(
    () => importSeedArticles({ db, seedPath: ghost }),
    (err) => err.code === 'SEED_FILE_MISSING' && err.message.includes('articles.js')
  );
});

test('malformed seed files raise SEED_PARSE_FAILED', () => {
  assert.throws(() => parseSeedSource('window.App = {};'), (e) => e.code === 'SEED_PARSE_FAILED');
  assert.throws(() => parseSeedSource('window.App.ArticleSeed = "not an array";'), (e) => e.code === 'SEED_PARSE_FAILED');
  assert.throws(() => parseSeedSource('window.App.ArticleSeed = [{"title": broken}];'), (e) => e.code === 'SEED_PARSE_FAILED');
});
